### ISSUE TITLE
[BUG] Duration of the meditations aren't shown correctly

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#419]
**Description:**
The duration of the meditations aren't shown correctly

**Steps to reproduce:**

1. Navigate to the List of Meditations

**Actual Result:**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/965f8935-c32a-4ef2-96fb-8c777416d96e)

**Expected Result:**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/65275689-d6e2-4d98-a22b-a775f9dc0e25)

**Comment by juanc-escobar** [comment]
Hi, @k-mlch it seems like it is already fixed:

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/bebf9fc2-c493-4261-b897-0a7846526ab5)

**Comment by k-mlch** [comment]
@juanc-escobar i'm not sure about this, because this bug was found by @Nanaier and even though i can't reproduce it, i believe it still appears for Anastasia

**Comment by juanc-escobar** [comment]
@k-mlch I believe it was fixed in the latest updates:



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/74a01be3-16fd-41c1-a7ac-81b9ff560cff)


let's check with @Nanaier if she still sees the issue.

**Comment by Nanaier** [comment]
I still have the same issue - I believe It is caused by the timezones

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90211108/346b0112-1935-40d5-86e7-17cd754ee3ac)

**Comment by v0ldemar01** [comment]
@Nanaier  if you don't have any assignments for now, can you please switch to this one and try to figure out the solution)

**Comment by juanc-escobar** [comment]
yes, I will un-assign myself from this one because I can not reproduce this error, I changed timezones in my PC but still the timers look good to me.

**Comment by oksana-mlynska** [comment]
@Nanaier now I see durations like this on my computer

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/79cbf8f3-9c77-4992-8e99-7d0ab78938f8)

**Comment by Nanaier** [comment]
@oksana-mlynska - I see, now that it was solved for me, It broke down for you - I'll try to solve it. If unsuccessful, I'll go back to the solution we had before

**Comment by oksana-mlynska** [comment]
@Nanaier Ok, thanks

**Comment by oksana-mlynska** [comment]
@Nanaier on my side everything is fine now both on PC and mobile device, so I guess I can close the issue
